### ISSUE TITLE
member_application_setting の name_UNIQUE_idx キー長が長すぎてテーブルの作成に失敗する

### ISSUE THREAD

**Issue by co3k** [openpne-ospt/opOpenSocialPlugin#14]
http://sns.openpne.jp/?m=pc&a=page_fh_diary&target_c_diary_id=22537 にて報告がありました
<pre><code>
# cp config/ProjectConfiguration.class.php.sample config/ProjectCo

nfiguration.class.php
# 　./symfony openpne:install

　　｜
　　｜
Is it OK to start this task? (y/n)
y

> > plugin installing plugin "opAuthMailAddressPlugin"
> > sfPearFrontendPlugin Attempting to discover channel "plugins.openpne.jp"...
> > 　　｜
> > 　　｜
> > 　　｜
> > 　　｜
> > doctrine created tables successfully

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes. Failing Query: CREATE TABLE member_application_setting (id BIGINT AUTO_INCREMENT, member_application_id BIGINT NOT NULL, type VARCHAR(255) DEFAULT 'application' NOT NULL, name VARCHAR(255) NOT NULL, value TEXT, UNIQUE INDEX name_UNIQUE_idx (member_application_id, type, name), INDEX member_application_id_idx (member_application_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 ENGINE = INNODB 
</pre></code>

**Comment by kawahara** [comment]
close
